# Generated by Django 4.2.5 on 2023-09-12 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_alter_curso_options_curso_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curso',
            options={'ordering': ('nombre', '-camada', '-fecha_creacion'), 'verbose_name': 'Course', 'verbose_name_plural': 'The Courses'},
        ),
        migrations.AlterModelOptions(
            name='estudiante',
            options={'ordering': ('nombre', '-apellido', '-email'), 'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
        migrations.AlterModelOptions(
            name='profesor',
            options={'ordering': ('nombre', '-apellido', '-email', '-profesion'), 'verbose_name': 'Teacher', 'verbose_name_plural': 'Teachers'},
        ),
        migrations.AlterUniqueTogether(
            name='estudiante',
            unique_together={('nombre', 'apellido', 'email')},
        ),
        migrations.AlterUniqueTogether(
            name='profesor',
            unique_together={('nombre', 'apellido', 'email', 'profesion')},
        ),
    ]
