# Generated by Django 4.2.5 on 2023-09-13 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0003_alter_curso_options_alter_estudiante_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entregable',
            options={'ordering': ('nombre', '-fechaDeEntrega'), 'verbose_name': 'Entregable', 'verbose_name_plural': 'Entregables'},
        ),
        migrations.AlterUniqueTogether(
            name='entregable',
            unique_together={('nombre', 'fechaDeEntrega')},
        ),
    ]
